[project]
name = "projectorEmbedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8, <3.9"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.7.5",
    "pyscf>=2.10.0",
]
